apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-node-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.172.202.235.132.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-helm-chart
                port:
                  number: 80
